-- Migration: Invalidate old Twitch OAuth tokens to force re-authentication with new scopes
-- Date: 2026-01-27
-- Reason: EventSub webhook support now requires additional OAuth scopes:
--   - channel:read:subscriptions (for sub/gift/resub events)
--   - bits:read (for cheer events)
--   - moderator:read:followers (for follow events)
--
-- NEUTERED 2026-06-13: this migration originally ran
--
--     UPDATE users SET token_expires_at = NOW()
--     WHERE auth_provider = 'twitch' AND token_expires_at > NOW();
--
-- as a ONE-TIME forced re-auth. But the migration runner
-- (scripts/run-migrations.sh) re-executes every migration on every pod
-- start, so this statement mass-expired ALL valid Twitch tokens on EVERY
-- deploy. Each deploy knocked every EventSub-partitioned channel back to
-- the IRC listener until token-refresh-service re-validated the tokens
-- (LIMIT 100 per 5-minute sweep), and any user whose refresh failed during
-- the churn was marked permanently failed and forced to re-authenticate.
--
-- The one-time re-auth this was written for completed in January 2026.
-- The statement must never run again. Guarded by
-- services/auth-service/repository/migrations_rerun_test.go, which applies
-- the full migration set twice and asserts a valid Twitch token survives.
SELECT 1;
