apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: twitch-listener
  namespace: allchat
  labels:
    app: twitch-listener
    component: listener
    platform: twitch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twitch-listener
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
