apiVersion: v1
kind: Service
metadata:
  name: tiktok-listener
  namespace: allchat
  labels:
    app: tiktok-listener
    component: listener
    platform: tiktok
spec:
  type: ClusterIP
  selector:
    app: tiktok-listener
  ports:
  - name: http
    port: 8089
    targetPort: 8089
    protocol: TCP
