---
apiVersion: v1
kind: Service
metadata:
  name: youtube-listener-innertube-stable
  namespace: allchat
  labels:
    app: youtube-listener-innertube
spec:
  selector:
    app: youtube-listener-innertube
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-listener-innertube-canary
  namespace: allchat
  labels:
    app: youtube-listener-innertube
spec:
  selector:
    app: youtube-listener-innertube
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
