#!/bin/bash
#
# Generate Ansible Vault from .env file
# This script reads your .env file and automatically creates secrets.vault.yml
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
VAULT_FILE="$SCRIPT_DIR/secrets.vault.yml"
VAULT_PASS_FILE="${HOME}/.ssh/ansible_vault_pass"

echo "================================================"
echo "All-Chat: Generate Vault from .env"
echo "================================================"
echo ""

# Check if .env exists
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ Error: .env file not found at: $ENV_FILE"
    echo ""
    echo "Please create a .env file from .env.example:"
    echo "  cp .env.example .env"
    echo "  # Then edit .env with your credentials"
    exit 1
fi

echo "✓ Found .env file at: $ENV_FILE"

# Source the .env file
set -a
source "$ENV_FILE"
set +a

echo "✓ Loaded environment variables"
echo ""

# Validate required variables
REQUIRED_VARS=(
    "TWITCH_CLIENT_ID"
    "TWITCH_CLIENT_SECRET"
    "TWITCH_BOT_USERNAME"
    "TWITCH_BOT_OAUTH"
    "JWT_SECRET"
    "TOKEN_ENCRYPTION_KEY"
)

MISSING_VARS=()
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        MISSING_VARS+=("$var")
    fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
    echo "⚠️  Warning: The following required variables are missing or empty in .env:"
    for var in "${MISSING_VARS[@]}"; do
        echo "  • $var"
    done
    echo ""
    read -p "Continue anyway? (y/n): " continue_anyway
    if [[ ! "$continue_anyway" =~ ^[Yy]$ ]]; then
        echo "Please update your .env file and try again."
        exit 1
    fi
fi

# Check if vault already exists
if [ -f "$VAULT_FILE" ]; then
    echo "⚠️  Warning: $VAULT_FILE already exists!"
    echo ""
    read -p "Overwrite? (y/n): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Keeping existing vault file."
        exit 0
    fi

    # If encrypted, decrypt first
    if head -n 1 "$VAULT_FILE" | grep -q '$ANSIBLE_VAULT'; then
        echo "Existing vault is encrypted. Decrypting..."
        if [ -f "$VAULT_PASS_FILE" ]; then
            ansible-vault decrypt "$VAULT_FILE" --vault-password-file "$VAULT_PASS_FILE" || {
                echo "❌ Failed to decrypt. Check password file: $VAULT_PASS_FILE"
                exit 1
            }
        else
            ansible-vault decrypt "$VAULT_FILE" || {
                echo "❌ Failed to decrypt. Wrong password?"
                exit 1
            }
        fi
    fi

    # Backup existing
    BACKUP_FILE="$VAULT_FILE.backup.$(date +%Y%m%d_%H%M%S)"
    mv "$VAULT_FILE" "$BACKUP_FILE"
    echo "✓ Backed up to: $BACKUP_FILE"
fi

# Generate vault file
echo "Generating secrets.vault.yml..."
echo ""

cat > "$VAULT_FILE" << EOF
---
# Ansible Vault for All-Chat
# Auto-generated from .env file on $(date)
# DO NOT EDIT THIS FILE DIRECTLY - Edit .env and regenerate

# =============================================================================
# DATABASE CREDENTIALS
# =============================================================================
postgres_password: "${DATABASE_PASSWORD:-allchat_dev_password}"

# =============================================================================
# JWT AUTHENTICATION
# =============================================================================
jwt_secret: "${JWT_SECRET:-dev-secret-change-in-production}"
jwt_expiry_hours: "24"
token_encryption_key: "${TOKEN_ENCRYPTION_KEY:-0123456789abcdef0123456789abcdef}"

# =============================================================================
# TWITCH INTEGRATION
# =============================================================================
twitch_client_id: "${TWITCH_CLIENT_ID}"
twitch_client_secret: "${TWITCH_CLIENT_SECRET}"
twitch_bot_username: "${TWITCH_BOT_USERNAME}"
twitch_bot_oauth: "${TWITCH_BOT_OAUTH}"
twitch_redirect_url: "${TWITCH_REDIRECT_URL:-http://localhost:8080/api/v1/auth/twitch/callback}"

# =============================================================================
# YOUTUBE INTEGRATION
# =============================================================================
youtube_client_id: "${YOUTUBE_CLIENT_ID:-your-youtube-client-id}"
youtube_client_secret: "${YOUTUBE_CLIENT_SECRET:-your-youtube-client-secret}"
youtube_redirect_url: "${YOUTUBE_REDIRECT_URL:-http://localhost:8080/api/v1/auth/youtube/callback}"
youtube_api_key: "${YOUTUBE_API_KEY:-}"

# =============================================================================
# CLUSTER CONFIGURATION
# =============================================================================
cluster_name: "allchat"
k3d_version: "v5.6.0"
kubectl_version: "v1.28.0"

# Port mappings
registry_port: 5000
api_port: 6443
http_port: 8080
https_port: 8443

# =============================================================================
# APPLICATION CONFIGURATION
# =============================================================================
log_level: "${LOG_LEVEL:-info}"
cors_origin: "${CORS_ALLOWED_ORIGINS:-http://localhost:3000}"
polling_interval_ms: "2000"
quota_limit_daily: "10000"

# Database connection
database_host: "postgres"
database_port: "${DATABASE_PORT:-5432}"
database_name: "${DATABASE_NAME:-allchat}"
database_user: "${DATABASE_USER:-allchat}"

# Redis connection
redis_host: "redis"
redis_port: "${REDIS_PORT:-6379}"
EOF

echo "✅ Generated secrets.vault.yml"
echo ""

# Show what was generated (sanitized)
echo "Generated configuration:"
echo ""
echo "Twitch OAuth:"
echo "  • Client ID: ${TWITCH_CLIENT_ID:0:10}..."
echo "  • Client Secret: ${TWITCH_CLIENT_SECRET:0:10}..."
echo "  • Bot Username: $TWITCH_BOT_USERNAME"
echo "  • Bot OAuth: ${TWITCH_BOT_OAUTH:0:15}..."
echo ""
echo "YouTube:"
echo "  • Client ID: ${YOUTUBE_CLIENT_ID:0:10}..."
echo "  • Client Secret: ${YOUTUBE_CLIENT_SECRET:0:10}..."
echo "  • API Key: ${YOUTUBE_API_KEY:0:10}..."
echo ""
echo "Security:"
echo "  • JWT Secret: ${JWT_SECRET:0:10}..."
echo "  • Database Password: ${DATABASE_PASSWORD:0:5}..."
echo ""
echo "Database: ${DATABASE_NAME:-allchat}@${DATABASE_HOST:-localhost}:${DATABASE_PORT:-5432}"
echo ""

# Ask if user wants to encrypt
read -p "Encrypt vault now? (recommended) (y/n): " encrypt_now

if [[ "$encrypt_now" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Encrypting vault..."

    if [ -f "$VAULT_PASS_FILE" ]; then
        echo "Using password from: $VAULT_PASS_FILE"
        ansible-vault encrypt "$VAULT_FILE" --vault-password-file "$VAULT_PASS_FILE"
    else
        echo "⚠️  Vault password file not found at: $VAULT_PASS_FILE"
        echo "You'll be prompted to create a vault password."
        echo ""
        ansible-vault encrypt "$VAULT_FILE"
    fi

    if [ $? -eq 0 ]; then
        echo ""
        echo "✅ Vault encrypted successfully!"
        echo ""
        echo "================================================"
        echo "Ready to Deploy!"
        echo "================================================"
        echo ""
        echo "Run the deployment script:"
        echo "  cd $SCRIPT_DIR"
        echo "  ./deploy.sh"
        echo ""
        echo "Or run Ansible directly:"
        echo "  ansible-playbook -i inventory.yml playbook.yml --vault-password-file $VAULT_PASS_FILE"
        echo ""
    else
        echo "❌ Encryption failed"
        exit 1
    fi
else
    echo ""
    echo "⚠️  Vault not encrypted!"
    echo "To encrypt later:"
    echo "  ansible-vault encrypt $VAULT_FILE --vault-password-file $VAULT_PASS_FILE"
    echo ""
fi

echo "================================================"
echo "Next Steps:"
echo "================================================"
echo ""
echo "1. Deploy the cluster:"
echo "   cd $SCRIPT_DIR"
echo "   ansible-playbook -i inventory.yml playbook.yml --ask-vault-pass"
echo ""
echo "2. If you update .env, regenerate vault:"
echo "   $0"
echo ""
echo "3. To edit vault manually:"
echo "   ansible-vault edit $VAULT_FILE"
echo ""
